# HashBook Config File

# 调试模式, 输出更多日志
debug: false

# 存储模式, 可以为 "file", "sqlite" 或 "mysql".
storage_mode: file

# 物品数据模式, 可以为 "nbt" 或 "pdc".
# NBT 模式需要依赖 NBTAPI
# PDC 模式只能在 Paper 上使用. Paper 端更推荐使用 PDC 模式.
item_data_mode: pdc

# 打开成书时立即设置哈希
set_hash_when_open_book: true