name: HashBook
version: '${version}'
main: xyz.xasmc.hashbook.HashBook
api-version: '1.20'

depend:
  - CommandAPI
softdepend:
  - NBTAPI

permissions:
  "xasmc.hashbook.command":
    default: true
  "xasmc.hashbook.command.reload":
    default: op
  "xasmc.hashbook.command.calchash":
    default: true
  "xasmc.hashbook.command.sethash":
    default: op
  "xasmc.hashbook.command.getpage":
    default: true
  "xasmc.hashbook.command.searchbook":
    default: true
  "xasmc.hashbook.command.storebook":
    default: true
  "xasmc.hashbook.command.bookinfo":
    default: true
