name: HashBook
version: '${version}'
main: xyz.xasmc.hashbook.HashBook
api-version: '1.18'

depend:
  - CommandAPI
softdepend:
  - NBTAPI

permissions:
  "xasmc.hashbook.command.sethash":
    default: op
  "xasmc.hashbook.command.reload":
    default: op
  "xasmc.hashbook.command.searchbook":
    default: op